baseURL = "https://duedissidence.com"
languageCode = "en-us"
title = "Due Dissidence"
disableKinds = ["taxonomy"]
summaryLength = 30
enableRobotsTXT = "true"
ignoreErrors = ["error-remote-getjson"]
ignoreLogs = ['shortcode-x-getremote']
[params]
  description = "Post Duopoly Left"
  author = "Due Dissidence"
[caches]
  [caches.images]
    dir = ':cacheDir/images'